cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

coupons/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply')
]

flower_shop/urls.py
# flower_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),

]

shop/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.models import Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Ваша корзина
{% endblock %}
{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить товар</th>
                <th>Цена одной штуки</th>
                <th>Стоимость</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            <tr>
                <td>
                    <a href="{{ item.product.get_absolute_url }}">
                        <img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ item.product.name }}">
                    </a>
                </td>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>
                    {% if item.product.id %}
                    <a href="{% url 'cart:cart_remove' item.product.id %}">Удалить</a>
                    {% else %}
                    ID товара отсутствует
                    {% endif %}
                </td>
                <td class="num">₽{{ item.price }}</td>
                <td class="num">₽{{ item.total_price }}</td>
            </tr>
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Промежуточный итог:</td>
                    <td colspan="4"></td>
                    <td class="num">₽{{ cart.get_total_price }}</td>
                </tr>
                <td>
                "{{ cart.coupon.code }}" купон
                ({{ cart.coupon.discount }}% скидка)
            </td>
            <td colspan="4"></td>
            <td class="num neg">
                - {{ cart.get_discount|floatformat:"2" }}
            </td>
    {% endif %}
    <tr class="total">
        <td>Итого: </td>
        <td colspan="4"></td>
        <td class="num">
            ₽{{ cart.get_total_price_after_discount|floatformat:"2" }}
        </td>
    </tr>
        </tbody>
    </table>
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Принять">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Продолжить покупки</a>
        <a href="{% url 'orders:order_create'%}" class="button">Перейти к оплате</a>
    </p>
{% endblock %}